version: '3.7'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./data/static:/app/static
    env_file:
      - ./.env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
    # comment volume section on OSX machines
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data:z

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./data/static:/app/static
    depends_on:
      - web
