# Generated by Django 3.0.3 on 2020-02-18 19:53

from django.db import migrations
from django.contrib.auth.models import User


def initial_data(apps, schema_editor):
    User.objects.create_superuser(username='admin', password='admin')
    User.objects.create_user(username='moderator', password='moderator')
    Cars = apps.get_model('core', 'Car')
    Cars.objects.create(model="kraz", car_number='123')
    Cars.objects.create(model="belaz", car_number='456')
    Cars.objects.create(model="kamaz", car_number='789')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]

